version: "3.7"
services:
  dev_db:
    image: postgres:12
    container_name: goplay_db_dev
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "goplay_db_dev"